server:
  port: 8080


spring:
  application:
    name: api-getway
  cloud:
    gateway:
      routes:
        - id: location-webservice
          uri: http://localhost:8081/
          predicates:
            - Path=/location-webservice/**
# eureka.client.serviceUrl.defaultZone: http://localhost:8761/
